import { StyleSheet } from 'react-native';

const colors = {
  errorColor: '#ef4000',
  primaryColor: '#292929',
  secondaryColor: '#929292',
  controlColor: '#212121',
  secondaryControlColor: '#ffb300',
  controlBackgroundColor: '#196394',
  lightDarkBackgroundColor: '#f1f1f1',
  controlTextColor: '#ffffff',
  darkText: '#032250',
  lightText: '#9fa0a8',
  cellBorder: '#EEEEEE',
  cellBorderDarker: '#787878',
  darkBackground: '#183E63',
  lightBackground: '#fff',
  borderLight: '#ccc',
  borderDark: '#000',
  driverMarkerColor: '#1fb6ff',
  riderMarkerColor: '#ffb200',
  destinationMarkerColor: '#15ff19',
  whiteColor: '#ffffff',
  infoText: '#929292',
  navigationBlue: '#4990e2',
  e6e6e6: '#e6e6e6',
  offlineBackgroundColor: 'rgba(74, 74, 74, 0.78)',
  acceptanceBackgroundColor: 'rgba(74, 74, 74, 0.50)',
  counterWarningColor: '#FFC107',
  disabledColor: '#878787',
  drawerBackgroundColor: '#1e1e1e',
  statusBarColor: '#222',
  lightBorder: '#98292929',
  total: '#4a4a4a',
  red: '#ff4630',
  green: '#7ed321',
  separationColor: '#f3f3f3',
  waitingColor: '#f3f3f3',
  settingBackground: '#f8f8f8',
  blackColor: '#000',
  waitingBackgroundColor: 'rgba(74, 74, 74, 0.78)',
  warning: '#f99a0e',
  orange: '#ff8400',
  pumpkin_orange: '#ff7d00',
  formColor: '#626262',
  statusLightBackgroundColor: '#fff',
  statusDarkBackgroundColor: '#000',
  warm_grey: '#8c8c8c',
  light_grey: '#ededed',
  dark_400: '#b6b6b6',
};

export default StyleSheet.create({
  changeCarPopUp: {
    height: '107%',
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    backgroundColor: colors.acceptanceBackgroundColor,
  },
  changeCarCard: {
    alignSelf: 'stretch',
    backgroundColor: '#fff',
    flexDirection: 'column',
    alignItems: 'center',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingTop: 8,
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 60,
  },
  topBar: {
    height: 2,
    width: 50,
    backgroundColor: '#E9E9E9',
  },
  titleLineContainer: {
    height: 40,
    alignSelf: 'stretch',
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    flexDirection: 'row',
  },
  closeIconContainer: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E9E9E9',
    borderRadius: 20,
  },
  titleText: {
    color: '#1B1B1B',
    fontSize: styles.FONT_SIZE_TITLE,
    fontFamily: styles.ROBOTO_MEDIUM,
  },
  carIdText: {
    color: '#5A5A5A',
    fontSize: styles.FONT_SIZE,
    fontFamily: styles.ROBOTO_THIN,
    marginTop: 8,
    marginBottom: 20,
  },
  carImage: {
    height: 80,
    width: 80,
    marginTop: 20,
  },
  carImageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 80,
    width: 80,
  },
  dateContainer: {
    height: 50,
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 8,
  },
  dateTextLineKey: {
    color: '#5A5A5A',
    fontSize: styles.FONT_SIZE,
    fontFamily: styles.ROBOTO_THIN,
  },
  dateTextLineValue: {
    color: '#1B1B1B',
    fontSize: styles.FONT_SIZE,
    fontFamily: styles.ROBOTO_THIN,
  },
  separatorBar: {
    height: 1,
    alignSelf: 'stretch',
    backgroundColor: '#E9E9E9',
  },
  buttonContainer: {
    marginTop: 20,
    height: 50,
    alignSelf: 'stretch',
    backgroundColor: '#1B1B1B',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E9E9E9',
  },
  buttonText: {
    color: '#fff',
    fontSize: styles.FONT_SIZE_TITLE,
    fontFamily: styles.ROBOTO_MEDIUM,
  },
});





